FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ForestManagement/ ./
RUN dotnet restore ForestManagement.sln
RUN dotnet publish WebApp/WebApp.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app ./
ENV ASPNETCORE_URLS=http://+:5255
EXPOSE 5255
ENTRYPOINT ["dotnet", "WebApp.dll"]
